### ISSUE TITLE
Duplicate sessions with different IDs

### ISSUE THREAD

**Issue by house92** [Fusion-Lifestyle/opendata#15]
The following two sessions appear to be identical but for their ID:

```
  {
    "state": "updated",
    "kind": "session",
    "id": "LH1SWS321000418",
    "modified": 393329224,
    "data": {
      "@context": [
        "https://www.openactive.io/ns/oa.jsonld",
        "https://www.openactive.io/ns-beta/oa.jsonld"
      ],
      "identifier": "LH1SWS321000418",
      "activity": "Pool Activities",
      "name": [
        "Lane Swim 21.00"
      ],
      "description": [],
      "genderRestriction": "mixed",
      "location": {
        "type": "Place",
        "url": "http://www.fusion-lifestyle.com/centres/leatherhead-leisure-centre",
        "name": "Leatherhead Leisure Centre",
        "identifier": "LEALC",
        "address": {
          "type": "PostalAddress",
          "postalCode": "KT22 9BL",
          "streetAddress": "Guildford Road"
        },
        "telephone": "01372 377674"
      },
      "subEvent": [
        {
          "type": "Event",
          "startDate": "2018-11-05T21:00:00Z",
          "endDate": "2018-11-05T21:59:59Z",
          "beta:availability": ">4",
          "maximumAttendeeCapacity": 30,
          "identifier": 370540022
        },
        {
          "type": "Event",
          "startDate": "2018-11-12T21:00:00Z",
          "endDate": "2018-11-12T21:59:59Z",
          "beta:availability": ">4",
          "maximumAttendeeCapacity": 30,
          "identifier": 370540023
        }
      ],
      "offer": [
        {
          "type": "Offer",
          "identifier": "STAND",
          "name": "Non Member",
          "description": "Casual Swim",
          "price": "4.90",
          "priceCurrency": "GBP",
          "beta:ageRange": "0",
          "genderRestriction": "mixed"
        },
        {
          "type": "Offer",
          "identifier": "NONJNR",
          "name": "Non Member Junior",
          "description": "Casual Swim",
          "price": "2.60",
          "priceCurrency": "GBP",
          "beta:ageRange": "0-15",
          "genderRestriction": "mixed"
        },
        {
          "type": "Offer",
          "identifier": "NONCON",
          "name": "Non Member Concession",
          "description": "Casual Swim",
          "price": "2.60",
          "priceCurrency": "GBP",
          "beta:ageRange": "16",
          "genderRestriction": "mixed"
        }
      ],
      "type": "Event",
      "duration": "PT1H"
    }
  }
```

```
  {
    "state": "updated",
    "kind": "session",
    "id": "LH1SWS421000418",
    "modified": 393331520,
    "data": {
      "@context": [
        "https://www.openactive.io/ns/oa.jsonld",
        "https://www.openactive.io/ns-beta/oa.jsonld"
      ],
      "identifier": "LH1SWS421000418",
      "activity": "Pool Activities",
      "name": [
        "Lane Swim 21.00"
      ],
      "description": [],
      "genderRestriction": "mixed",
      "location": {
        "type": "Place",
        "url": "http://www.fusion-lifestyle.com/centres/leatherhead-leisure-centre",
        "name": "Leatherhead Leisure Centre",
        "identifier": "LEALC",
        "address": {
          "type": "PostalAddress",
          "postalCode": "KT22 9BL",
          "streetAddress": "Guildford Road"
        },
        "telephone": "01372 377674"
      },
      "subEvent": [
        {
          "type": "Event",
          "startDate": "2018-11-05T21:00:00Z",
          "endDate": "2018-11-05T21:59:59Z",
          "beta:availability": ">4",
          "maximumAttendeeCapacity": 30,
          "identifier": 370540098
        },
        {
          "type": "Event",
          "startDate": "2018-11-12T21:00:00Z",
          "endDate": "2018-11-12T21:59:59Z",
          "beta:availability": ">4",
          "maximumAttendeeCapacity": 30,
          "identifier": 370540099
        }
      ],
      "offer": [
        {
          "type": "Offer",
          "identifier": "STAND",
          "name": "Non Member",
          "description": "Casual Swim",
          "price": "4.90",
          "priceCurrency": "GBP",
          "beta:ageRange": "0",
          "genderRestriction": "mixed"
        },
        {
          "type": "Offer",
          "identifier": "NONJNR",
          "name": "Non Member Junior",
          "description": "Casual Swim",
          "price": "2.60",
          "priceCurrency": "GBP",
          "beta:ageRange": "0-15",
          "genderRestriction": "mixed"
        },
        {
          "type": "Offer",
          "identifier": "NONCON",
          "name": "Non Member Concession",
          "description": "Casual Swim",
          "price": "2.60",
          "priceCurrency": "GBP",
          "beta:ageRange": "16",
          "genderRestriction": "mixed"
        }
      ],
      "type": "Event",
      "duration": "PT1H"
    }
  }
```

There are other such duplicates, which have presented a problem for our UX. Is this a fairly straightforward problem for you to resolve or might it take more time?

**Comment by FusionLifestyle** [comment]
Hi Sam,

The configuration of the one was wrong. Suppose to be not web bookable but the option was on. We have now corrected.



Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Hi Thanos, hope you're well.

Just wanted to follow-up on @house92's initial point. We still appear to be receiving duplicate swimming sessions, with time, date, location and session name all the same, but with different `id` and `subEvent: identifier`.

For example, session ids `GL1SSOL14000418` and `GL1SSOF14000418` both refer to "General Swim" at Golden Lane on 2018-11-27 from 14:00:00-15:59:59.

Any thoughts greatly appreciated. @FusionLIfestyle

**Comment by FusionLifestyle** [comment]
Hi Roz,

Seems that this is same issue as last week. Wrong configuration.

Can you please correct as I tried and I did not find how..

@Dom Fennell<mailto:Dom@imin.co> Please send me a list of all these issues and we will fix.

[cid:image003.jpg@01D480D2.3F359270]


Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Hi Thanos (@FusionLIfestyle), hope you're having a good week.

We're still seeing the duplicate sessions in our platform and just wanted to check if the necessary changes have been made your end?

Many thanks,

Dom

**Comment by FusionLifestyle** [comment]
Hi Roz,

Can you please fix the below?



Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

From: Thanos Lempesis
Sent: 20 November 2018 13:09
To: 'Fusion-Lifestyle/opendata' <reply@reply.github.com>; 'Fusion-Lifestyle/opendata' <opendata@noreply.github.com>; 'Dom Fennell' <Dom@imin.co>
Cc: 'Mention' <mention@noreply.github.com>; Keiron Butcher <Keiron.Butcher@fusion-lifestyle.com>
Subject: RE: [Fusion-Lifestyle/opendata] Duplicate sessions with different IDs (#15)

Hi Roz,

Seems that this is same issue as last week. Wrong configuration.

Can you please correct as I tried and I did not find how..

@Dom Fennell<mailto:Dom@imin.co> Please send me a list of all these issues and we will fix.

[cid:image003.jpg@01D48706.4CF5FCD0]


Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Hi Thanos (@FusionLIfestyle), hope you had a good weekend.

We're still seeing the duplicate sessions in our platform and just wanted to check if the necessary changes have been made your end?

Very best,

Dom

**Comment by FusionLifestyle** [comment]
Hi Roz,

Can you please assist?



Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

From: Thanos Lempesis
Sent: 28 November 2018 10:37
To: 'Fusion-Lifestyle/opendata' <reply@reply.github.com>; 'Fusion-Lifestyle/opendata' <opendata@noreply.github.com>; 'Dom Fennell' <Dom@imin.co>
Cc: 'Mention' <mention@noreply.github.com>; Keiron Butcher <Keiron.Butcher@fusion-lifestyle.com>
Subject: RE: [Fusion-Lifestyle/opendata] Duplicate sessions with different IDs (#15)

Hi Roz,

Can you please fix the below?



Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

From: Thanos Lempesis
Sent: 20 November 2018 13:09
To: 'Fusion-Lifestyle/opendata' <reply@reply.github.com>; 'Fusion-Lifestyle/opendata' <opendata@noreply.github.com<mailto:opendata@noreply.github.com>>; 'Dom Fennell' <Dom@imin.co<mailto:Dom@imin.co>>
Cc: 'Mention' <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Keiron Butcher <Keiron.Butcher@fusion-lifestyle.com<mailto:Keiron.Butcher@fusion-lifestyle.com>>
Subject: RE: [Fusion-Lifestyle/opendata] Duplicate sessions with different IDs (#15)

Hi Roz,

Seems that this is same issue as last week. Wrong configuration.

Can you please correct as I tried and I did not find how..

@Dom Fennell<mailto:Dom@imin.co> Please send me a list of all these issues and we will fix.

[cid:image003.jpg@01D48AFE.29C0BB50]


Kind Regards,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Hi Thanos (@FusionLIfestyle), hope you had a good weekend.

Any news on this? Hopefully we can get it sorted before everyone breaks for the festive holidays.

Very best,

Dom

**Comment by FusionLifestyle** [comment]
Hi Dom,

I have forwarded this to @Roz Crabtree<mailto:Roz.Crabtree@fusion-lifestyle.com> a couple of times so she will respond to you after fixing this upon her availability.


Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by FusionLifestyle** [comment]
Actioned.


Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

From: Thanos Lempesis
Sent: 10 December 2018 16:03
To: 'Fusion-Lifestyle/opendata' <reply@reply.github.com>; Fusion-Lifestyle/opendata <opendata@noreply.github.com>; Roz Crabtree <Roz.Crabtree@fusion-lifestyle.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Fusion-Lifestyle/opendata] Duplicate sessions with different IDs (#15)

Hi Dom,

I have forwarded this to @Roz Crabtree<mailto:Roz.Crabtree@fusion-lifestyle.com> a couple of times so she will respond to you after fixing this upon her availability.


Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Hi Thanos, thanks for your efforts (and apologies for bothering you intermittently about this!). When you say "actioned", what do you mean? @FusionLIfestyle

**Comment by FusionLifestyle** [comment]
I mean that this specific incident has been corrected. If there are more please provide more details as you did with the previous “duplicated” sessions:


For example, session ids GL1SSOL14000418 and GL1SSOF14000418 both refer to "General Swim" at Golden Lane on 2018-11-27 from 14:00:00-15:59:59.



Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Hi Thanos (@FusionLIfestyle),

Some more examples as requested:

- GL7SSOL08000418 and GL7SSOF08000418 both refer to "Lane Swim" at Golden Lane on 2018-12-16 from 08:00:00-09:59:59;
- GL7SSOL10000418 and GL7SSOF10000418 both refer to "General Swim" at Golden Lane on 2018-12-16 from 10:00:00-15:59:59;
- GL6SSOL16000418 and GL6SSOF16000418 both refer to "Family Swim" at Golden Lane on 2018-12-16 from 16:00:00-16:59:59; and
- GL6SSOF17000418 and GL6SSOL17000418 both refer to "Lane Swim" at Golden Lane on 2018-12-16 from 17:00:00-17:44:59.

Of course, do please let me know if you think is in an issue our side.

Thanks and best,

Dom

**Comment by domfennell** [comment]
Thanks, Thanos (@FusionLIfestyle). I will do just that.

Out of interest, why will this not the case in a few weeks?

**Comment by FusionLifestyle** [comment]
Hi Dom,

Long story short, we re-build MRM and moving to a new DB. Configuration access will be limited to well-trained and centralized team so data will be cleaner, readable, make sense and consistent.


Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by domfennell** [comment]
Thanks for summarising, Thanos (@FusionLIfestyle). Makes sense. Hope the build & move both go well. In the meantime, I'll continue to let you know about the duplicated sessions.

Have a good day,

Dom

**Comment by domfennell** [comment]
Thanks for summarising, Thanos (@FusionLIfestyle). Makes sense. Hope the build & move both go well. In the meantime, I'll continue to let you know about the duplicated sessions.

Just one other question: the sessions you want me to alert you to have different IDs, as noted earlier. What about duplicated sessions that have identical IDs, for example, `GS6BANDS1100` & `GS6BANDS1500` (both of which have 2 instances in our platform), and `GS6BANDS0900` (which has 4 instances in our platform)? Do you think this is an issue our side?

Thanks,

Dom

**Comment by FusionLifestyle** [comment]
Actioned!



Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by FusionLifestyle** [comment]
Hi Dom,

I can see that in Table [openactive_pushed_sessions] all these are unique so does not seem to be an issue with the data that the service publishes..

@'Nick Evans'<mailto:nick.evans@theodi.org> any thought on that?


[cid:image001.png@01D492C9.D0ED9560]


Many thanks,

Thanos Lempesis
Applications & Development Manager

[cid:image001.jpg@01CDD13F.CDC1D6F0]<http://www.fusion-lifestyle.com/>
Unit 4, Bickels Yard, 151/153 Bermondsey Street, London, SE1 3HA.
T:   020 7740 7524
M: 07825 663294
www.fusion-lifestyle.com<https://217.151.104.114/exchweb/bin/redir.asp?URL=https://217.151.104.114/exchweb/bin/redir.asp?URL=http://www.fusion-lifestyle.com/>
P Think before you print to save energy and paper.

**Comment by nickevansuk** [comment]
@FusionLIfestyle @domfennell excellent find!

There was indeed the possibility of duplicate sessions occurring after extended running of the old version of OWS. Really great catch!

We've just fixed this in the new version of OWS based on this bug report, so that fix will get applied to Fusion when we do the next install.

Great work!
